version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - '2181:2181'
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: 'test-topic:1:1'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka-producer:
    image: kafka-producer
    ports:
      - '3000:3000'
    environment:
      KAFKA_TOPIC: 'test-topic'
      KAFKA_BROKER: 'kafka:9092'
    depends_on:
      - kafka
  kafka-consumer:
    image: kafka-consumer
    depends_on:
      - kafka
    environment:
      KAFKA_TOPIC: 'test-topic'
      KAFKA_BROKER: 'kafka:9092'
